import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import SiteHeader from "@/components/admin/site-header";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} antialiased`}>
        <SiteHeader />
        {children}
      </body>
    </html>
  );
}
